######
# Config file for sc cacoa scripts
#

BASE_FP: "/omics/odcf/analysis/OE0228_projects/VascularAging/rna_sequencing/public_scrnaseq"
DATASET: "Mouse_lung"
FILENAME: "kimmel_lung"

download_link: 
  link: "https://storage.googleapis.com/calico-website-mca-storage/lung.h5ad"
  f_type: "h5ad"
  GEO: ""

organism: "mm"

cacoa_opts:
  id_field: "mouse.id"
  age_field: "age"
  Ident: "cell_type"
  regroup_age: False