######
# Config file for sc cacoa scripts
#

BASE_FP: "/omics/odcf/analysis/OE0228_projects/VascularAging/rna_sequencing/public_scrnaseq"
DATASET: "TabularMuris_nonmyeloid_brain"
FILENAME: "senis_facs_brain"


download_link: 
  link: "https://figshare.com/ndownloader/files/23872787"
  f_type: "h5ad"
  GEO: ""

organism: "mm"

cacoa_opts:
  id_field: "mouse.id"
  age_field: "age"
  Ident: "cell_ontology_class"
  regroup_age: True